<template>
  <BentoCard 
    title="Основная информация" 
    size="1x1" 
    variant="default"
  >
    <FormV2 
      :show-actions="false"
      submit-text=""
      reset-text=""
    >
      <div class="space-y-6">
        
        <!-- ШАГ 1: Тип списка (самое важное решение) -->
        <FormFieldV2 
          type="custom"
          label="Тип списка"
          required
          :hint="isEditMode ? 'Тип списка нельзя изменить в режиме редактирования' : 'Выберите тип списка в зависимости от назначения'"
          :error="formErrors.type"
        >
          <div class="space-y-3">
            <label 
              class="flex items-start gap-3 p-4 border rounded-lg transition-colors"
              :class="[
                { 'border-primary bg-primary/5': formData.type === 'custom' },
                isEditMode ? 'opacity-60 cursor-not-allowed' : 'cursor-pointer hover:bg-gray-50'
              ]"
            >
              <input 
                type="radio" 
                :checked="formData.type === 'custom'"
                @change="() => { formData.type = 'custom'; handleTypeChange(); }"
                :disabled="isEditMode"
                class="mt-1 disabled:opacity-50 disabled:cursor-not-allowed"
              />
              <div>
                <div class="font-medium text-primary">🆓 Кастомный список</div>
                <div class="text-sm text-secondary">
                  Произвольный список оборудования, не привязанный к конкретному мероприятию
                </div>
              </div>
            </label>
            
            <label 
              class="flex items-start gap-3 p-4 border rounded-lg transition-colors"
              :class="[
                { 'border-primary bg-primary/5': formData.type === 'security' },
                isEditMode ? 'opacity-60 cursor-not-allowed' : 'cursor-pointer hover:bg-gray-50'
              ]"
            >
              <input 
                type="radio" 
                :checked="formData.type === 'security'"
                @change="() => { formData.type = 'security'; handleTypeChange(); }"
                :disabled="isEditMode"
                class="mt-1 disabled:opacity-50 disabled:cursor-not-allowed"
              />
              <div>
                <div class="font-medium text-primary">🔒 Список для охраны</div>
                <div class="text-sm text-secondary">
                  Список привязанный к конкретному мероприятию и точке монтажа для нужд охраны
                </div>
              </div>
            </label>
          </div>
        </FormFieldV2>

        <!-- ШАГ 2: Детали списка (зависят от типа) -->
        <div v-if="formData.type" class="space-y-4 p-4 bg-gray-50 border border-gray-200 rounded-lg">
          <div class="flex items-center gap-2 mb-3">
            <span class="text-primary">✏️</span>
            <h4 class="font-medium text-primary">Детали списка</h4>
          </div>

          <!-- Название для кастомного списка -->
          <FormFieldV2 
            v-if="formData.type === 'custom'"
            type="text"
            :model-value="formData.name"
            @update:model-value="handleNameChange"
            label="Название списка"
            required
            placeholder="Например: Оборудование для сцены А"
            :error="formErrors.name"

          />

          <!-- Название для security списка -->
          <div v-if="formData.type === 'security'">
            <!-- В режиме создания: автогенерация -->
            <FormFieldV2 
              v-if="!isEditMode"
              type="custom"
              label="Название списка"
              hint="Название генерируется автоматически на основе выбранного мероприятия и точки монтажа"
            >
              <div class="p-3 bg-white border border-gray-300 rounded-md">
                <div class="text-sm font-medium text-primary break-words leading-relaxed">
                  {{ autoGeneratedName || 'Выберите мероприятие и точку монтажа для генерации названия' }}
                </div>
              </div>
            </FormFieldV2>
            
            <!-- В режиме редактирования: обычное поле ввода -->
            <FormFieldV2 
              v-else
              type="text"
              label="Название списка"
              hint="Вы можете изменить название списка"
              :model-value="formData.name"
              @update:model-value="handleNameChange"
              required
              :error="formErrors.name"
              placeholder="Введите название списка"
            />
            

          </div>

          <!-- Описание для кастомного списка -->
          <FormFieldV2 
            v-if="formData.type === 'custom'"
            type="textarea"
            :model-value="formData.description"
            @update:model-value="handleDescriptionChange"
            label="Описание"
            hint="Краткое описание назначения списка"
            placeholder="Опишите для чего предназначен этот список..."
            :rows="3"
            :error="formErrors.description"

          />

          <!-- Автогенерируемое описание для security списка -->
          <FormFieldV2 
            v-if="formData.type === 'security'"
            type="custom"
            label="Описание"
            hint="Описание генерируется автоматически"
          >
            <div class="p-3 bg-white border border-gray-300 rounded-md">
              <div class="text-sm text-secondary">
                {{ autoGeneratedDescription || 'Описание будет сгенерировано после выбора мероприятия и точки монтажа' }}
              </div>
            </div>
          </FormFieldV2>
        </div>

      </div>
    </FormV2>
  </BentoCard>
</template>

<script setup>
/**
 * ListBasicInfoForm - EPR System
 * 
 * Компонент формы основной информации для создания списков оборудования
 * Включает выбор типа списка и соответствующие поля
 * 
 * @component
 * @example
 * <ListBasicInfoForm
 *   :form-data="formData"
 *   :form-errors="formErrors"
 *   :auto-generated-name="autoName"
 *   :auto-generated-description="autoDesc"
 *   @update:form-data="handleFormDataUpdate"
 *   @update:form-errors="handleFormErrorsUpdate"
 *   @type-change="handleTypeChange"
 * />
 */

import { 
  BentoCard,
  FormV2,
  FormFieldV2
} from '@/shared/ui-v2'

// ===== PROPS =====
const props = defineProps({
  formData: {
    type: Object,
    required: true,
    validator: (value) => {
      return typeof value === 'object' && 
             value !== null &&
             'type' in value &&
             'name' in value &&
             'description' in value
    }
  },
  formErrors: {
    type: Object,
    default: () => ({})
  },
  autoGeneratedName: {
    type: String,
    default: ''
  },
  autoGeneratedDescription: {
    type: String,
    default: ''
  },
  isEditMode: {
    type: Boolean,
    default: false
  }
})

// ===== EMITS =====
const emit = defineEmits([
  'update:form-data',
  'update:form-errors',
  'type-change'
])

// ===== МЕТОДЫ =====
const handleTypeChange = () => {
  console.log('📝 [ListBasicInfoForm] Изменен тип списка:', props.formData.type)
  
  // Эмитируем событие изменения типа для родительского компонента
  emit('type-change', props.formData.type)
  
  // Очищаем ошибки при изменении типа
  const newErrors = { ...props.formErrors }
  delete newErrors.type
  delete newErrors.name
  delete newErrors.description
  emit('update:form-errors', newErrors)
}

const handleNameChange = (value) => {
  console.log('📝 [ListBasicInfoForm] Изменено название:', value)
  
  const updatedFormData = {
    ...props.formData,
    name: value
  }
  emit('update:form-data', updatedFormData)
  
  // Очищаем ошибку названия если она была
  if (props.formErrors.name) {
    const newErrors = { ...props.formErrors }
    delete newErrors.name
    emit('update:form-errors', newErrors)
  }
}

const handleDescriptionChange = (value) => {
  console.log('📝 [ListBasicInfoForm] Изменено описание:', value)
  
  const updatedFormData = {
    ...props.formData,
    description: value
  }
  emit('update:form-data', updatedFormData)
  
  // Очищаем ошибку описания если она была
  if (props.formErrors.description) {
    const newErrors = { ...props.formErrors }
    delete newErrors.description
    emit('update:form-errors', newErrors)
  }
}
</script>

<style scoped>
/* UI Kit v2 + Bento Grid стили */

/* Плавные переходы для радио кнопок */
.cursor-pointer {
  transition: all 0.2s ease;
}

.cursor-pointer:hover {
  transform: translateY(-1px);
  box-shadow: 0 2px 4px rgba(0, 0, 0, 0.05);
}

/* Активное состояние */
.border-primary {
  box-shadow: 0 0 0 3px rgba(59, 130, 246, 0.1);
}

/* Стабилизация layout */
.space-y-6 > * + * {
  margin-top: 1.5rem;
}

.space-y-4 > * + * {
  margin-top: 1rem;
}

.space-y-3 > * + * {
  margin-top: 0.75rem;
}
</style>