/**
 * useListCreation - EPR System
 * 
 * Composable для управления состоянием и логикой создания/редактирования списков оборудования
 * Централизует всю бизнес-логику, валидацию и вычисляемые свойства
 * 
 * @param {string|null} editListId - ID списка для редактирования (опционально)
 * @returns {Object} Объект с состоянием и методами для создания/редактирования списков
 */

import { ref, computed } from 'vue'
import { getEquipmentListById } from '@/features/equipment/api/equipment-lists-api.js'

export function useListCreation(editListId = null) {
  // ===== РЕЖИМ РАБОТЫ =====
  const isEditMode = computed(() => !!editListId)
  const listId = ref(editListId)
  // ===== СОСТОЯНИЕ ФОРМЫ =====
  const formData = ref({
    name: '',
    description: '',
    type: 'custom', // 'custom' | 'security'
    event_id: null,
    mount_point_id: null,
    equipment_ids: []
  })

  const formErrors = ref({})
  const createLoading = ref(false)
  const loadingListData = ref(false) // Для загрузки данных при редактировании

  // ===== ДАННЫЕ ДЛЯ АВТОГЕНЕРАЦИИ =====
  const selectedEventName = ref('')
  const selectedMountPointName = ref('')

  // ===== ВЫЧИСЛЯЕМЫЕ СВОЙСТВА =====
  
  // Автогенерация названия для security списков (ТОЛЬКО в режиме создания)
  const autoGeneratedName = computed(() => {
    // В режиме редактирования НЕ автогенерируем название
    if (isEditMode.value) {
      return ''
    }
    
    if (formData.value.type !== 'security' || 
        !formData.value.event_id || 
        !formData.value.mount_point_id) {
      return ''
    }
    
    return `${selectedMountPointName.value} - ${selectedEventName.value}`
  })

  // Автогенерация описания для security списков (ТОЛЬКО в режиме создания)
  const autoGeneratedDescription = computed(() => {
    // В режиме редактирования НЕ автогенерируем описание
    if (isEditMode.value) {
      return ''
    }
    
    if (formData.value.type !== 'security' || 
        !formData.value.event_id || 
        !formData.value.mount_point_id) {
      return ''
    }
    
    return `Автоматически созданный список оборудования для точки монтажа "${selectedMountPointName.value}" в рамках мероприятия "${selectedEventName.value}"`
  })

  // Проверка готовности к созданию списка
  const canCreateList = computed(() => {
    console.log('🔍 [useListCreation] Проверка готовности списка:', {
      type: formData.value.type,
      name: formData.value.name,
      event_id: formData.value.event_id,
      mount_point_id: formData.value.mount_point_id,
      equipment_count: formData.value.equipment_ids.length
    })
    
    // КРИТИЧЕСКИ ВАЖНО - должно быть выбрано оборудование
    if (!formData.value.equipment_ids || formData.value.equipment_ids.length === 0) {
      console.log('❌ [useListCreation] Нет выбранного оборудования')
      return false
    }
    
    // Для кастомных списков - проверяем что есть название
    if (formData.value.type === 'custom') {
      const isReady = formData.value.name?.trim() && 
                     formData.value.type && 
                     formData.value.equipment_ids.length > 0
      console.log('🆓 [useListCreation] Кастомный список готов:', isReady)
      return isReady
    }
    
    // Для security списков - проверяем что выбраны мероприятие и точка монтажа
    if (formData.value.type === 'security') {
      const isReady = formData.value.type && 
                     formData.value.event_id && 
                     formData.value.mount_point_id &&
                     formData.value.equipment_ids.length > 0
      console.log('🔒 [useListCreation] Security список готов:', isReady)
      return isReady
    }
    
    console.log('❌ [useListCreation] Неизвестный тип списка')
    return false
  })

  // Прогресс заполнения формы
  const progressPercentage = computed(() => {
    let progress = 0
    
    // Базовый прогресс: тип выбран
    if (formData.value.type) {
      progress += 20
      
      // Для кастомных списков
      if (formData.value.type === 'custom') {
        // Название введено = +25%
        if (formData.value.name?.trim()) progress += 25
        
        // Оборудование выбрано = +25%
        if (formData.value.equipment_ids.length > 0) progress += 25
        
        // Все готово = +30%
        if (formData.value.name?.trim() && formData.value.equipment_ids.length > 0) {
          progress += 30
        }
      }
      
      // Для security списков
      else if (formData.value.type === 'security') {
        // Мероприятие выбрано = +20%
        if (formData.value.event_id) progress += 20
        
        // Точка монтажа выбрана = +20%
        if (formData.value.mount_point_id) progress += 20
        
        // Оборудование выбрано = +20%
        if (formData.value.equipment_ids.length > 0) progress += 20
        
        // Все готово = +20%
        if (formData.value.event_id && 
            formData.value.mount_point_id && 
            formData.value.equipment_ids.length > 0) {
          progress += 20
        }
      }
    }
    
    return Math.min(progress, 100)
  })

  // ===== МЕТОДЫ ВАЛИДАЦИИ =====
  
  const validateForm = () => {
    formErrors.value = {}
    
    // КРИТИЧЕСКИ ВАЖНО - проверяем наличие оборудования ПЕРВЫМ ДЕЛОМ
    if (!formData.value.equipment_ids || formData.value.equipment_ids.length === 0) {
      formErrors.value.equipment_ids = 'Список не может быть пустым. Выберите хотя бы одну единицу оборудования'
      console.log('❌ [validateForm] Список оборудования пустой')
    }
    
    // Название обязательно только для кастомных списков
    if (formData.value.type === 'custom' && !formData.value.name?.trim()) {
      formErrors.value.name = 'Название списка обязательно'
    }
    
    if (!formData.value.type) {
      formErrors.value.type = 'Выберите тип списка'
    }
    
    if (formData.value.type === 'security') {
      if (!formData.value.event_id) {
        formErrors.value.event_id = 'Выберите мероприятие'
      }
      if (!formData.value.mount_point_id) {
        formErrors.value.mount_point_id = 'Выберите точку монтажа'
      }
    }
    
    const isValid = Object.keys(formErrors.value).length === 0
    console.log('🔍 [validateForm] Результат валидации:', isValid, formErrors.value)
    return isValid
  }

  // ===== МЕТОДЫ ОБНОВЛЕНИЯ СОСТОЯНИЯ =====
  
  const updateFormData = (newData) => {
    formData.value = { ...formData.value, ...newData }
    console.log('📝 [useListCreation] Данные формы обновлены:', formData.value)
  }

  const updateFormErrors = (newErrors) => {
    formErrors.value = { ...newErrors }
    console.log('⚠️ [useListCreation] Ошибки формы обновлены:', formErrors.value)
  }

  const updateSelectedEquipment = (equipmentIds) => {
    console.log('📦 [updateSelectedEquipment] Начинаем обновление:', {
      input: equipmentIds,
      inputLength: equipmentIds?.length || 0,
      beforeUpdate: formData.value.equipment_ids?.length || 0
    })
    
    formData.value.equipment_ids = equipmentIds || []
    
    console.log('📦 [updateSelectedEquipment] Обновление завершено:', {
      finalLength: formData.value.equipment_ids?.length || 0,
      canCreate: formData.value.equipment_ids?.length > 0
    })
  }

  const updateLinkedData = ({ eventId, eventName, mountPointId, mountPointName }) => {
    if (eventId !== undefined) {
      formData.value.event_id = eventId
      selectedEventName.value = eventName || ''
    }
    
    if (mountPointId !== undefined) {
      formData.value.mount_point_id = mountPointId
      selectedMountPointName.value = mountPointName || ''
    }
    
    console.log('🔗 [useListCreation] Связанные данные обновлены:', {
      event: selectedEventName.value,
      mountPoint: selectedMountPointName.value
    })
  }

  // ===== МЕТОДЫ ОБРАБОТКИ ИЗМЕНЕНИЙ =====
  
  const handleTypeChange = (newType) => {
    console.log('🔄 [useListCreation] Изменен тип списка:', newType)
    
    if (newType === 'custom') {
      // Очищаем связанные поля
      formData.value.event_id = null
      formData.value.mount_point_id = null
      selectedEventName.value = ''
      selectedMountPointName.value = ''
      
      // Если переходим с security на custom и не было введенного названия - очищаем
      if (!formData.value.name || formData.value.name.startsWith('Список оборудования')) {
        formData.value.name = ''
        formData.value.description = ''
      }
    } else if (newType === 'security') {
      // Если переходим на security - очищаем введенные данные (они будут автогенерированы)
      formData.value.name = ''
      formData.value.description = ''
    }
    
    // Очищаем ошибки при смене типа
    const newErrors = { ...formErrors.value }
    delete newErrors.type
    delete newErrors.name
    delete newErrors.description
    delete newErrors.event_id
    delete newErrors.mount_point_id
    formErrors.value = newErrors
  }

  // ===== МЕТОДЫ СБРОСА =====
  
  const resetForm = () => {
    console.log('🧹 [useListCreation] Сброс формы к исходному состоянию')
    
    // Сбрасываем данные формы
    formData.value = {
      name: '',
      description: '',
      type: 'custom',
      event_id: null,
      mount_point_id: null,
      equipment_ids: []
    }
    
    // Очищаем ошибки валидации
    formErrors.value = {}
    
    // Очищаем создание
    createLoading.value = false
    
    // Очищаем связанные данные
    selectedEventName.value = ''
    selectedMountPointName.value = ''
  }

  // ===== МЕТОДЫ ДЛЯ РЕЖИМА РЕДАКТИРОВАНИЯ =====
  
  // Заполнение формы данными списка
  const populateFormWithListData = async (listData, getEventName, getMountPointName, loadMountPoints) => {
    console.log('📝 [Edit] Заполнение формы данными:', listData)
    console.log('📝 [Edit] listData.name:', listData.name)
    console.log('📝 [Edit] Структура listData:', Object.keys(listData))
    console.log('📝 [Edit] КРИТИЧНО - listData.equipment_ids:', listData.equipment_ids)
    console.log('📝 [Edit] КРИТИЧНО - тип equipment_ids:', typeof listData.equipment_ids)
    console.log('📝 [Edit] КРИТИЧНО - Array.isArray(equipment_ids):', Array.isArray(listData.equipment_ids))
    
    // Основная информация
    formData.value.name = listData.name || ''
    formData.value.description = listData.description || ''
    formData.value.type = listData.type || 'custom'
    formData.value.event_id = listData.event_id || null
    formData.value.mount_point_id = listData.mount_point_id || null
    
    // Парсим equipment_ids если это строка JSON
    let equipmentIds = listData.equipment_ids || []
    if (typeof equipmentIds === 'string') {
      try {
        equipmentIds = JSON.parse(equipmentIds)
        console.log('📝 [Edit] equipment_ids было строкой, распарсили в:', equipmentIds)
      } catch (error) {
        console.error('❌ [Edit] Ошибка парсинга equipment_ids как JSON:', error)
        equipmentIds = []
      }
    }
    
    formData.value.equipment_ids = Array.isArray(equipmentIds) ? equipmentIds : []
    
    console.log('📝 [Edit] После заполнения formData.name:', formData.value.name)
    console.log('📝 [Edit] После заполнения formData.type:', formData.value.type)
    console.log('📝 [Edit] КРИТИЧНО - После заполнения formData.equipment_ids:', formData.value.equipment_ids)
    console.log('📝 [Edit] КРИТИЧНО - Длина equipment_ids:', formData.value.equipment_ids.length)
    
    // Для security списков загружаем названия event и mount point
    if (listData.type === 'security' && listData.event_id) {
      try {
        console.log('🔄 [Edit] Загружаем названия для security списка')
        
        // Получаем название события
        selectedEventName.value = getEventName(listData.event_id)
        console.log('📅 [Edit] Название события:', selectedEventName.value)
        
        // Для получения названия точки монтажа нужно сначала загрузить точки для события
        if (listData.mount_point_id && loadMountPoints) {
          await loadMountPoints(listData.event_id)
          selectedMountPointName.value = getMountPointName(listData.mount_point_id)
          console.log('📍 [Edit] Название точки монтажа:', selectedMountPointName.value)
        }
      } catch (error) {
        console.error('❌ [Edit] Ошибка загрузки названий:', error)
      }
    }
    
    console.log('✅ [Edit] Форма заполнена данными списка')
  }

  const loadListForEdit = async (id, dependencies = {}) => {
    if (!id) return
    
    try {
      loadingListData.value = true
      console.log('🔄 [Edit] Загрузка списка для редактирования:', id)
      
      // Загружаем данные списка из API
      const listData = await getEquipmentListById(id)
      console.log('📊 [Edit] Данные списка получены:', listData)
      
      // Заполняем форму данными с зависимостями для получения названий
      await populateFormWithListData(
        listData, 
        dependencies.getEventName, 
        dependencies.getMountPointName,
        dependencies.loadMountPoints
      )
      
    } catch (error) {
      console.error('❌ [Edit] Ошибка загрузки списка:', error)
      formErrors.value.general = 'Не удалось загрузить данные списка: ' + error.message
    } finally {
      loadingListData.value = false
    }
  }

  // ===== ПУБЛИЧНЫЙ API =====
  return {
    // Состояние
    formData,
    formErrors,
    createLoading,
    loadingListData, // Для режима редактирования
    
    // Режим работы
    isEditMode,
    listId,
    
    // Вычисляемые свойства
    autoGeneratedName,
    autoGeneratedDescription,
    canCreateList,
    progressPercentage,
    
    // Методы валидации
    validateForm,
    
    // Методы обновления
    updateFormData,
    updateFormErrors,
    updateSelectedEquipment,
    updateLinkedData,
    
    // Методы обработки
    handleTypeChange,
    
    // Методы сброса
    resetForm,
    
    // Методы редактирования
    loadListForEdit,
    populateFormWithListData
  }
}