<template>
  <div class="min-h-screen bg-accent">
    <!-- Header с Breadcrumbs -->
    <div class="bg-white border-b border-gray-200">
      <div class="max-w-7xl mx-auto px-4 py-4">
        <BreadcrumbsV2 
          :items="breadcrumbs" 
          variant="minimal" 
          size="sm"
          @item-click="handleBreadcrumbClick"
          @navigate="handleBreadcrumbNavigate"
        />
        
        <div class="flex justify-between items-center mt-4">
          <div>
            <h1 class="text-2xl font-bold text-primary">
              {{ isEditMode ? 'Редактирование списка оборудования' : 'Создание списка оборудования' }}
            </h1>
            <p class="text-sm text-secondary mt-1">
              {{ isEditMode 
                ? 'Измените информацию о списке и составе оборудования' 
                : 'Создайте новый список оборудования, выберите оборудование из таблицы' 
              }}
            </p>
          </div>
          
          <ButtonV2 
            variant="ghost"
            size="md"
            @click="navigateBack"
          >
            <template #icon>
              <span class="text-sm">←</span>
            </template>
            Назад к спискам
          </ButtonV2>
        </div>
      </div>
    </div>

    <!-- Main Content в Bento Grid -->
    <div class="max-w-7xl mx-auto px-4 py-6">
      <div class="grid gap-4 grid-cols-1 md:grid-cols-[2fr_1fr] contain-layout">
        
        <!-- Настройки (Mobile: полная ширина, Desktop: левая колонка) -->
        <div class="space-y-4 md:space-y-6">
          
          <!-- 1. Основная информация -->
          <ListBasicInfoForm
            :form-data="formData"
            :form-errors="formErrors"
            :auto-generated-name="autoGeneratedName"
            :auto-generated-description="autoGeneratedDescription"
            :is-edit-mode="isEditMode"
            @update:form-data="updateFormData"
            @update:form-errors="updateFormErrors"
            @type-change="handleTypeChange"
          />

          <!-- 2. Связанные данные (только для security списков) -->
          <ListLinkedDataForm
            :form-data="formData"
            :form-errors="formErrors"
            :event-options="eventOptions"
            :mount-point-options="mountPointOptions"
            :events-loading="eventsLoading"
            :mount-points-loading="mountPointsLoading"
            :events-error="eventsError"
            :mount-points-error="mountPointsError"
            :conflict-info="conflictInfo"
            @update:form-data="updateFormData"
            @update:form-errors="updateFormErrors"
            @event-change="handleEventChange"
            @mount-point-change="handleMountPointChange"
          />

          <!-- 3. Поиск и фильтры -->
          <EquipmentSearchFilters
            :search-query="searchQuery"
            :selected-category="selectedCategory"
            :selected-subcategory="selectedSubcategory"
            :search-suggestions="searchSuggestions"
            :search-loading="searchLoading"
            :equipment-categories="equipmentCategories"
            @search="handleSearch"
            @search-select="handleSearchSelect"
            @search-clear="handleSearchClear"
            @category-change="handleCategoryChange"
            @subcategory-change="handleSubcategoryChange"
            @clear-filters="handleClearFilters"
          />

          <!-- Информация о конфликтах -->
          <div v-if="formData.type === 'security' && formData.event_id && hasConflicts" 
               class="bg-amber-50 border border-amber-200 rounded-lg p-4 mb-4">
            
            <!-- Заголовок с кнопкой раскрытия -->
            <div class="flex items-center justify-between">
              <div class="flex items-center gap-3">
                <div class="flex-shrink-0">
                  <IconV2 name="alert-triangle" size="md" color="warning" />
                </div>
                <div>
                  <h4 class="font-semibold text-amber-800">
                    Обнаружено зарезервированное оборудование
                  </h4>
                  <p class="text-sm text-amber-700">
                    Зарезервировано <strong>{{ conflictedEquipmentCount }}</strong> единиц оборудования
                  </p>
                </div>
              </div>
              
              <!-- Кнопка раскрытия/сворачивания -->
              <button
                @click="showConflictDetails = !showConflictDetails"
                class="flex items-center gap-1 px-3 py-1 text-xs font-medium text-amber-700 bg-amber-100 hover:bg-amber-200 rounded-md transition-colors duration-200"
              >
                <span>{{ showConflictDetails ? 'Скрыть' : 'Показать' }} детали</span>
                <IconV2 
                  :name="showConflictDetails ? 'chevron-up' : 'chevron-down'" 
                  size="xs" 
                  color="warning" 
                />
              </button>
            </div>

            <!-- Детальная информация (сворачиваемая) -->
            <div 
              v-if="showConflictDetails"
              class="mt-4 pt-4 border-t border-amber-200 transition-all duration-300 ease-in-out"
            >
              <p class="text-sm text-amber-700 mb-3">
                Подробная информация по зарезервированному оборудованию:
              </p>
              <div class="space-y-2">
                <div v-for="stat in conflictStats" :key="stat.listName" 
                     class="flex items-center justify-between text-sm bg-amber-100/50 rounded-md p-2">
                  <span class="text-amber-700">
                    • Список "{{ stat.listName }}" ({{ stat.mountPointName }})
                  </span>
                  <span class="font-medium text-amber-800">{{ stat.equipmentCount }} единиц</span>
                </div>
              </div>
              <p class="text-xs text-amber-600 mt-3 p-2 bg-amber-100/30 rounded-md">
                💡 <strong>Справка:</strong> Зарезервированное оборудование будет заблокировано для выбора в таблице ниже и отмечено иконкой замка.
              </p>
            </div>
          </div>

          <!-- 4. Таблица с выбором оборудования -->
          <EquipmentTableWithSelection
            :data="equipments"
            :loading="equipmentLoading || conflictsLoading"
            :error="equipmentError || conflictsError"
            :current-page="currentPage"
            :total-pages="totalPages"
            :items-per-page="itemsPerPage"
            :total="totalEquipmentCount"
            :sort-by="sortBy"
            :sort-order="sortOrder"
            :selected-ids="selectedEquipmentIds"
            :conflict-info="conflictInfo"
            @sort="handleSort"
            @page-change="handlePageChange"
            @items-per-page-change="handleItemsPerPageChange"
            @selection-change="handleSelectionChange"
          />

        </div>

        <!-- Действия и превью (Mobile: снизу, Desktop: правая колонка) -->
        <div class="order-first md:order-last">
          <div class="space-y-4 md:space-y-6">
            
            <!-- Панель создания -->
            <ListCreationActions
              :form-data="formData"
              :can-create-list="canCreateList"
              :progress-percentage="progressPercentage"
              :create-loading="createLoading"
              :auto-generated-name="autoGeneratedName"
              :selected-equipment-count="selectedEquipmentIds.length"
              :event-name="getEventName(formData.event_id)"
              :is-mobile="isMobile"
              :is-edit-mode="isEditMode"
              @create-list="handleCreateList"
              @reset-form="handleResetForm"
              @cancel="navigateBack"
            />

            <!-- Предварительный просмотр выбранного оборудования -->
            <div class="md:sticky md:top-6 md:z-10">
              <SelectedEquipmentPreview
                :selected-equipment="selectedEquipmentData"
                @remove="handleRemoveEquipment"
                @clear-all="handleClearSelection"
                @export-list="handleExportList"
              />
            </div>

          </div>
        </div>

      </div>
    </div>

    <!-- Notification System -->
    <NotificationV2 ref="notificationSystem" position="top-right" />
  </div>
</template>

<script setup>
/**
 * EquipmentListsCreatePage - EPR System (Refactored)
 * 
 * Рефакторенная страница создания списков оборудования
 * Использует разделённые компоненты и composable для логики
 */

import { ref, computed, onMounted, onBeforeUnmount, watch } from 'vue'
import { useRouter } from 'vue-router'
import { useBreakpoints } from '@vueuse/core'
import { debounce } from 'lodash-es'

// UI Kit v2
import { 
  BreadcrumbsV2, 
  ButtonV2, 
  IconV2,
  NotificationV2 
} from '@/shared/ui-v2'

// Новые компоненты
import ListBasicInfoForm from './components/list-creation/ListBasicInfoForm.vue'
import ListLinkedDataForm from './components/list-creation/ListLinkedDataForm.vue'
import ListCreationActions from './components/list-creation/ListCreationActions.vue'
import { useListCreation } from './components/list-creation/useListCreation.js'

// Существующие компоненты
import EquipmentSearchFilters from './components/EquipmentSearchFilters.vue'
import EquipmentTableWithSelection from '@/features/equipment/components/EquipmentTableWithSelection.vue'
import SelectedEquipmentPreview from '@/features/equipment/components/SelectedEquipmentPreview.vue'

// Stores и API
import { useEquipmentStore } from '@/features/equipment'
import { useAuthStore } from '@/app/store/auth-store'
import { EQUIPMENT_CATEGORIES } from '@/features/equipment/constants/categories.js'
import { createEquipmentList, updateEquipmentList } from '@/features/equipment/api/equipment-lists-api.js'
import { useEquipmentListsData } from '@/features/equipment/composables/useEquipmentListsData'
import { useEquipmentReservation } from './composables/useEquipmentReservation.js'

const router = useRouter()
const equipmentStore = useEquipmentStore()
const authStore = useAuthStore()

// ===== ПАРАМЕТРЫ РОУТА =====
const props = defineProps({
  id: {
    type: String,
    default: null
  }
})

// ===== КОМПОЗИЦИАЛЬНАЯ ЛОГИКА =====
const {
  formData,
  formErrors,
  createLoading,
  loadingListData,
  isEditMode,
  listId,
  autoGeneratedName,
  autoGeneratedDescription,
  canCreateList,
  progressPercentage,
  validateForm,
  updateFormData,
  updateFormErrors,
  updateSelectedEquipment,
  updateLinkedData,
  handleTypeChange: handleTypeChangeLogic,
  resetForm,
  loadListForEdit
} = useListCreation(props.id) // Передаем ID для режима редактирования

// ===== АДАПТИВНОСТЬ =====
const breakpoints = useBreakpoints({
  sm: 640,
  md: 768,
  lg: 1024,
  xl: 1280,
})

const isMobile = breakpoints.smaller('md')

// ===== BREADCRUMBS =====
const breadcrumbs = [
  { label: 'Главная', href: '/', icon: 'home' },
  { 
    label: 'Модуль оборудования', 
    href: '/equipment',
    submenu: [
      { label: '🔧 Управление оборудованием', href: '/equipment/items', icon: 'settings' },
      { label: '📋 Списки оборудования', href: '/equipment/lists', icon: 'list' },
      { label: '➕ Создать список', href: '/equipment/lists/create', icon: 'plus' }
    ]
  },
  { label: 'Списки оборудования', href: '/equipment/lists' },
  { label: isEditMode ? 'Редактирование списка' : 'Создание списка', disabled: true }
]

// ===== ВЫБОР ОБОРУДОВАНИЯ =====
const selectedEquipmentIds = ref([])

// ===== UI СОСТОЯНИЕ =====
const showConflictDetails = ref(false)

// ===== РЕЗЕРВИРОВАНИЕ ОБОРУДОВАНИЯ =====
const {
  conflictInfo,
  conflictsLoading,
  conflictsError,
  hasConflicts,
  conflictedEquipmentCount,
  conflictStats,
  setEvent,
  loadConflicts,
  isEquipmentConflicted,
  getEquipmentConflictInfo,
  canAddEquipment,
  getConflictMessage,
  clearConflicts
} = useEquipmentReservation()

// Сбрасываем состояние показа деталей при очистке конфликтов
watch(hasConflicts, (newValue) => {
  if (!newValue) {
    showConflictDetails.value = false
  }
})

// ===== ПОИСК И ФИЛЬТРЫ =====
const searchQuery = ref('')
const selectedCategory = ref('')
const selectedSubcategory = ref('')
const searchSuggestions = ref([])
const searchLoading = ref(false)

// ===== ДАННЫЕ ТАБЛИЦЫ =====
const equipmentLoading = computed(() => equipmentStore.loading)
const equipmentError = computed(() => equipmentStore.error)
const equipments = computed(() => equipmentStore.equipments)
const currentPage = computed(() => equipmentStore.currentPage)
const totalPages = computed(() => equipmentStore.totalPages)
const itemsPerPage = computed(() => equipmentStore.itemsPerPage)
const totalEquipmentCount = computed(() => equipmentStore.total)
const sortBy = computed(() => equipmentStore.sortBy)
const sortOrder = computed(() => equipmentStore.sortOrder)

// ===== ДАННЫЕ СПИСКОВ =====
const {
  eventOptions,
  mountPointOptions,
  eventsLoading,
  mountPointsLoading,
  eventsError,
  mountPointsError,
  loadMountPoints,
  clearMountPoints,
  getEventName,
  getMountPointName,
  initialize: initializeListsData
} = useEquipmentListsData()

const notificationSystem = ref(null)
const equipmentCategories = EQUIPMENT_CATEGORIES

// ===== ОТДЕЛЬНОЕ ХРАНИЛИЩЕ ДЛЯ ВЫБРАННОГО ОБОРУДОВАНИЯ =====
const selectedEquipmentCache = ref(new Map()) // Map<id, equipmentData>

// ===== COMPUTED =====
const selectedEquipmentData = computed(() => {
  // Сначала ищем в кэше выбранного оборудования
  const fromCache = selectedEquipmentIds.value
    .map(id => selectedEquipmentCache.value.get(id))
    .filter(Boolean)
  
  // Потом ищем в основном store (для новых добавлений)
  const fromStore = equipments.value.filter(equipment => 
    selectedEquipmentIds.value.includes(equipment.id) && 
    !selectedEquipmentCache.value.has(equipment.id)
  )
  
  // Добавляем найденные в store элементы в кэш
  fromStore.forEach(equipment => {
    selectedEquipmentCache.value.set(equipment.id, equipment)
  })
  
  return [...fromCache, ...fromStore]
})

// ===== МЕТОДЫ =====

// Поиск и фильтры
const debouncedSearch = debounce(async (query) => {
  await equipmentStore.setSearchQuery(query)
}, 300)

const debouncedSuggestions = debounce(async (query) => {
  if (!query || query.length < 2) {
    searchSuggestions.value = []
    return
  }
  
  searchLoading.value = true
  try {
    const suggestions = await equipmentStore.getSearchSuggestions(query)
    searchSuggestions.value = suggestions
  } catch (error) {
    console.error('Ошибка получения автокомплита:', error)
    searchSuggestions.value = []
  } finally {
    searchLoading.value = false
  }
}, 150)

const handleSearch = (query) => {
  searchQuery.value = query
  debouncedSearch(query)
  debouncedSuggestions(query)
}

const handleSearchSelect = (suggestion) => {
  searchQuery.value = suggestion.value
  debouncedSearch(suggestion.value)
  searchSuggestions.value = []
}

const handleSearchClear = () => {
  searchQuery.value = ''
  searchSuggestions.value = []
  debouncedSearch.cancel()
  debouncedSuggestions.cancel()
  equipmentStore.setSearchQuery('')
}

const handleCategoryChange = async (category) => {
  selectedCategory.value = category
  selectedSubcategory.value = ''
  await equipmentStore.setFilters({ type: category, subtype: '' })
}

const handleSubcategoryChange = async (subcategory) => {
  selectedSubcategory.value = subcategory
  await equipmentStore.setFilters({ 
    type: selectedCategory.value, 
    subtype: subcategory 
  })
}

const handleClearFilters = async () => {
  searchQuery.value = ''
  selectedCategory.value = ''
  selectedSubcategory.value = ''
  searchSuggestions.value = []
  debouncedSearch.cancel()
  debouncedSuggestions.cancel()
  await equipmentStore.setSearchQuery('')
  await equipmentStore.clearFilters()
}

// Таблица
const handleSort = async (sortEvent) => {
  console.log('🔄 [Create] Sort event received:', sortEvent)
  // НЕ передаем direction, позволяем store самому управлять логикой переключения
  await equipmentStore.setSorting(sortEvent.column)
}

const handlePageChange = async (page) => {
  await equipmentStore.setPage(page)
}

const handleItemsPerPageChange = async (items) => {
  await equipmentStore.setItemsPerPage(items)
}

// Выбор оборудования
const handleSelectionChange = (newSelectedIds) => {
  console.log('🔄 [Selection] Новые выбранные IDs:', newSelectedIds)
  console.log('🔄 [Selection] Режим редактирования:', isEditMode.value)
  
  // Фильтруем конфликтное оборудование
  const validIds = newSelectedIds.filter(id => canAddEquipment(id))
  
  // Показываем предупреждение если было отфильтровано оборудование
  if (validIds.length !== newSelectedIds.length) {
    const blockedCount = newSelectedIds.length - validIds.length
    notificationSystem.value?.warning(
      `${blockedCount} единиц оборудования не может быть добавлено - уже зарезервировано для этого мероприятия`,
      {
        title: 'Оборудование зарезервировано',
        duration: 4000
      }
    )
  }
  
  // ПРОВЕРЯЕМ попытку очистить весь список
  if (validIds.length === 0 && (formData.value.equipment_ids?.length > 0 || selectedEquipmentIds.value.length > 0)) {
    console.log('⚠️ [Selection] Попытка очистить весь список')
    console.log('⚠️ [Selection] validIds:', validIds.length)
    console.log('⚠️ [Selection] formData.equipment_ids:', formData.value.equipment_ids?.length)
    console.log('⚠️ [Selection] selectedEquipmentIds:', selectedEquipmentIds.value.length)
    
    // Показываем предупреждение, но ПОЗВОЛЯЕМ очистку
    notificationSystem.value?.warning('Внимание: список будет пустым. Выберите оборудование для сохранения.', {
      title: 'Список пуст',
      duration: 3000
    })
    
    // КРИТИЧЕСКОЕ ИСПРАВЛЕНИЕ: Продолжаем выполнение, НЕ делаем return
    // Это позволит обновить formData.equipment_ids = [] и заблокировать кнопку
    console.log('✅ [Selection] Разрешаем очистку - кнопка заблокируется автоматически')
  }
  
  // В ОБОИХ режимах теперь точно отражаем выбор пользователя
  console.log('📝 [Selection] Обновляем выбор оборудования')
  
  // Обновляем кэш выбранного оборудования
  const currentSelectedIds = new Set(selectedEquipmentIds.value)
  const updatedSelectedIds = new Set(validIds)
  
  // Добавляем новые элементы в кэш
  validIds.forEach(id => {
    if (!currentSelectedIds.has(id)) {
      const equipment = equipments.value.find(eq => eq.id === id)
      if (equipment && !selectedEquipmentCache.value.has(id)) {
        selectedEquipmentCache.value.set(id, equipment)
        console.log('📝 [Selection] Добавлено в кэш:', equipment.brand, equipment.model)
      }
    }
  })
  
  // Удаляем элементы из кэша, которые больше не выбраны
  selectedEquipmentIds.value.forEach(id => {
    if (!updatedSelectedIds.has(id)) {
      selectedEquipmentCache.value.delete(id)
      console.log('📝 [Selection] Удалено из кэша:', id)
    }
  })
  
  selectedEquipmentIds.value = validIds
  updateSelectedEquipment(validIds)
  console.log('📝 [Selection] Финальные IDs:', validIds.length)
  console.log('📝 [Selection] Размер кэша:', selectedEquipmentCache.value.size)
  console.log('🔍 [Selection] canCreateList после изменения:', canCreateList.value)
}

const handleRemoveEquipment = (equipmentId) => {
  console.log('🗑️ [Remove] Удаляем оборудование:', equipmentId)
  console.log('🗑️ [Remove] Текущие IDs:', selectedEquipmentIds.value)
  
  const newIds = selectedEquipmentIds.value.filter(id => id !== equipmentId)
  console.log('🗑️ [Remove] IDs после фильтрации:', newIds)
  
  // КРИТИЧЕСКАЯ ПРОВЕРКА - не удаляем последнюю единицу оборудования
  if (newIds.length === 0) {
    console.log('❌ [Remove] БЛОКИРОВАНО: Попытка удалить последнюю единицу')
    notificationSystem.value?.error('Список не может быть пустым. Оставьте хотя бы одну единицу оборудования.', {
      title: 'Ошибка валидации',
      duration: 4000
    })
    return // НЕ удаляем, если это последняя единица
  }
  
  // АТОМАРНОЕ обновление - сначала selectedEquipmentIds, потом formData
  selectedEquipmentIds.value = newIds
  updateSelectedEquipment(newIds)
  
  // Удаляем из кэша выбранного оборудования
  selectedEquipmentCache.value.delete(equipmentId)
  console.log('🗑️ [Remove] Удалено из кэша. Размер кэша:', selectedEquipmentCache.value.size)
  
  console.log('✅ [Remove] Успешно удалено. Осталось:', newIds.length)
  console.log('🔍 [Remove] canCreateList после удаления:', canCreateList.value)
}

const handleClearSelection = () => {
  console.log('🧹 [Clear] Попытка очистить выбор оборудования')
  
  // В режиме редактирования не позволяем полностью очистить список
  if (isEditMode.value && selectedEquipmentIds.value.length > 0) {
    notificationSystem.value?.error('Список не может быть пустым. Оставьте хотя бы одну единицу оборудования.', {
      title: 'Ошибка валидации',
      duration: 4000
    })
    return // НЕ очищаем список в режиме редактирования
  }
  
  console.log('🧹 [Clear] Очищаем выбор оборудования')
  // Прямое обновление без вызова handleSelectionChange
  selectedEquipmentIds.value = []
  updateSelectedEquipment([])
  
  // Очищаем кэш выбранного оборудования
  selectedEquipmentCache.value.clear()
  console.log('🧹 [Clear] Кэш выбранного оборудования очищен')
}

const handleExportList = () => {
  console.log('Экспорт списка')
}

// Связанные данные
const handleEventChange = async (eventId) => {
  const eventName = getEventName(eventId)
  updateLinkedData({ eventId, eventName })
  
  formData.value.mount_point_id = null
  
  if (eventId) {
    await loadMountPoints(eventId)
  } else {
    clearMountPoints()
  }
  
  // КРИТИЧЕСКИ ВАЖНО: Загружаем конфликты при изменении мероприятия
  if (eventId && formData.value.type === 'security') {
    console.log('🎯 [EventChange] Загружаем конфликты для мероприятия:', eventId)
    // В режиме редактирования передаем ID текущего списка чтобы исключить его из конфликтов
    setEvent(eventId, isEditMode.value ? props.id : null)
  } else {
    console.log('🧹 [EventChange] Очищаем конфликты')
    clearConflicts()
  }
}

const handleMountPointChange = (mountPointId) => {
  const mountPointName = getMountPointName(mountPointId)
  updateLinkedData({ mountPointId, mountPointName })
}

const handleTypeChange = (newType) => {
  handleTypeChangeLogic(newType)
  
  // При изменении типа на security - загружаем конфликты если есть мероприятие
  if (newType === 'security' && formData.value.event_id) {
    console.log('🎯 [TypeChange] Тип изменился на security, загружаем конфликты для мероприятия:', formData.value.event_id)
    // В режиме редактирования передаем ID текущего списка чтобы исключить его из конфликтов
    setEvent(formData.value.event_id, isEditMode.value ? props.id : null)
  } else if (newType !== 'security') {
    console.log('🧹 [TypeChange] Тип изменился на не-security, очищаем конфликты')
    clearConflicts()
  }
}

// Создание/редактирование и навигация
const handleCreateList = async () => {
  console.log('🔄 [handleCreateList] Начинаем валидацию...')
  console.log('🔄 [handleCreateList] Текущие IDs оборудования:', formData.value.equipment_ids)
  console.log('🔄 [handleCreateList] Количество оборудования:', formData.value.equipment_ids?.length || 0)
  
  // ТРОЙНАЯ ПРОВЕРКА - абсолютно критично
  if (!formData.value.equipment_ids || formData.value.equipment_ids.length === 0) {
    console.log('❌ [handleCreateList] БЛОКИРОВАНО: Список оборудования пустой')
    notificationSystem.value?.error('КРИТИЧЕСКАЯ ОШИБКА: Список не может быть пустым. Выберите хотя бы одну единицу оборудования', {
      title: 'Ошибка валидации',
      duration: 6000
    })
    return
  }
  
  if (!validateForm()) {
    console.log('❌ [handleCreateList] БЛОКИРОВАНО: Валидация формы не пройдена')
    notificationSystem.value?.error('Заполните все обязательные поля', {
      title: 'Ошибка валидации',
      duration: 4000
    })
    return
  }
  
  // Дополнительная проверка на случай если equipment_ids каким-то образом стал пустым
  if (!formData.value.equipment_ids || formData.value.equipment_ids.length === 0) {
    console.log('❌ [handleCreateList] БЛОКИРОВАНО: Повторная проверка - список оборудования пустой')
    notificationSystem.value?.error('ПОВТОРНАЯ ОШИБКА: Список не может быть пустым. Выберите хотя бы одну единицу оборудования', {
      title: 'Критическая ошибка валидации',
      duration: 6000
    })
    return
  }
  
  console.log('✅ [handleCreateList] Все проверки пройдены, продолжаем...')
  
  createLoading.value = true
  
  try {
    // Проверяем авторизацию
    if (!authStore.isAuthenticated || !authStore.user?.id) {
      throw new Error('Пользователь не авторизован')
    }

    const listData = {
      name: formData.value.type === 'security' && !isEditMode.value ? autoGeneratedName.value : formData.value.name,
      description: formData.value.type === 'security' && !isEditMode.value ? autoGeneratedDescription.value : formData.value.description,
      type: formData.value.type,
      equipment_ids: formData.value.equipment_ids,
      event_id: formData.value.event_id,
      mount_point_id: formData.value.mount_point_id
    }
    
    // В режиме создания добавляем данные о создателе
    if (!isEditMode.value) {
      listData.created_by = authStore.user.id
      listData.metadata = {
        created_by_name: authStore.user.name || authStore.user.email || 'Неизвестный пользователь',
        created_by_role: authStore.role,
        version: '1.0'
      }
    }
    
    let result
    if (isEditMode.value) {
      // Режим редактирования - обновляем существующий список
      console.log('🔄 Обновление списка ID:', props.id)
      result = await updateEquipmentList(props.id, listData)
    } else {
      // Режим создания - создаем новый список
      console.log('✨ Создание нового списка')
      result = await createEquipmentList(listData)
    }
    
    notificationSystem.value?.success(
      isEditMode.value ? 'Список оборудования успешно обновлен!' : 'Список оборудования успешно создан!', 
      {
        title: 'Успех',
        duration: 4000
      }
    )
    
    router.push('/equipment/lists')
    
  } catch (error) {
    console.error('❌ Ошибка', isEditMode.value ? 'обновления' : 'создания', 'списка:', error)
    
    let errorMessage = 'Произошла неизвестная ошибка'
    if (error.message) {
      errorMessage = error.message
    } else if (error.code) {
      errorMessage = `Ошибка базы данных: ${error.code}`
    }
    
    notificationSystem.value?.error(
      `Не удалось ${isEditMode.value ? 'обновить' : 'создать'} список: ${errorMessage}`, 
      {
        title: isEditMode.value ? 'Ошибка обновления' : 'Ошибка создания',
        duration: 5000
      }
    )
  } finally {
    createLoading.value = false
  }
}

const handleResetForm = () => {
  resetForm()
  selectedEquipmentIds.value = []
  conflictInfo.value = {}
  searchQuery.value = ''
  selectedCategory.value = ''
  selectedSubcategory.value = ''
  searchSuggestions.value = []
  
  // Отменяем все debounced функции
  debouncedSearch.cancel()
  debouncedSuggestions.cancel()
  
  clearMountPoints()
  equipmentStore.setPage(1)
  
  notificationSystem.value?.info('Все поля возвращены к исходному состоянию', {
    title: 'Форма сброшена'
  })
}

// Навигация
const handleBreadcrumbClick = (data) => {
  if (data.isSubmenu) {
    if (data.item.href) {
      router.push(data.item.href)
    }
    return
  }
  
  if (data.item.href && !data.item.disabled) {
    router.push(data.item.href)
  }
}

const handleBreadcrumbNavigate = (data) => {
  if (data.href) {
    router.push(data.href)
  }
}

const navigateBack = () => {
  router.push('/equipment/lists')
}

// ===== LIFECYCLE =====
onMounted(async () => {
  console.log('🏁 [Page] Монтирование страницы. Режим:', isEditMode.value ? 'редактирование' : 'создание')
  
  // Очищаем кэш при монтировании для свежего старта
  selectedEquipmentCache.value.clear()
  
  // Инициализируем authStore если он не инициализирован
  if (!authStore.isAuthenticated && !authStore.session) {
    await authStore.init()
  }
  
  // В режиме редактирования загружаем данные списка ПЕРВЫМ делом
  if (isEditMode.value && props.id) {
    console.log('📝 [Page] Режим редактирования. Загружаем список:', props.id)
    
    // Передаем зависимости для получения названий событий и точек монтажа
    await loadListForEdit(props.id, {
      getEventName,
      getMountPointName, 
      loadMountPoints
    })
    
    // После загрузки данных синхронизируем выбранное оборудование (ОДНОРАЗОВО при загрузке)
    selectedEquipmentIds.value = [...(formData.value.equipment_ids || [])]
    console.log('🔄 [Page] Синхронизированы IDs оборудования:', selectedEquipmentIds.value.length)
    console.log('🔍 [Page] canCreateList после загрузки:', canCreateList.value)
    
    // КРИТИЧНО: Загружаем конкретные единицы оборудования по ID для отображения
    if (selectedEquipmentIds.value.length > 0) {
      console.log('🔄 [Page] Загружаем оборудование для отображения в режиме редактирования')
      try {
        const { getEquipmentByIds } = await import('@/features/equipment/api/equipment-external-data-api')
        const result = await getEquipmentByIds(selectedEquipmentIds.value)
        if (result.data && Array.isArray(result.data)) {
          // Добавляем загруженное оборудование в отдельный кэш для выбранного оборудования
          result.data.forEach(equipment => {
            selectedEquipmentCache.value.set(equipment.id, equipment)
          })
          console.log('✅ [Page] Оборудование загружено в кэш для отображения:', result.data.length, 'единиц')
          console.log('✅ [Page] Размер кэша выбранного оборудования:', selectedEquipmentCache.value.size)
        }
      } catch (error) {
        console.error('❌ [Page] Ошибка загрузки оборудования для отображения:', error)
      }
    }
  }
  
  await Promise.all([
    equipmentStore.loadEquipments(),
    initializeListsData()
  ])
  
  if (eventsError.value) {
    notificationSystem.value?.error(`Не удалось загрузить мероприятия: ${eventsError.value}`, {
      title: 'Ошибка загрузки'
    })
  }
  
  console.log('📋 Страница создания/редактирования списков оборудования инициализирована (refactored)')
})

// ===== CLEANUP =====
onBeforeUnmount(() => {
  console.log('🧹 [Page] Размонтирование - очищаем кэш выбранного оборудования')
  selectedEquipmentCache.value.clear()
})

// ===== WATCHERS =====
// УДАЛЯЕМ ЦИКЛИЧЕСКИЙ WATCHER - он создает конфликты!
// selectedEquipmentIds управляется напрямую через handleSelectionChange/handleRemoveEquipment
// formData.equipment_ids обновляется через updateSelectedEquipment

// Следим за изменениями мероприятия и типа для загрузки конфликтов
watch([() => formData.value.event_id, () => formData.value.type], ([newEventId, newType]) => {
  console.log('🔄 [Watch] Мероприятие или тип изменились:', { eventId: newEventId, type: newType })
  
  if (newEventId && newType === 'security') {
    console.log('✅ [Watch] Условия выполнены, загружаем конфликты')
    // В режиме редактирования передаем ID текущего списка чтобы исключить его из конфликтов
    setEvent(newEventId, isEditMode.value ? props.id : null)
  } else {
    console.log('❌ [Watch] Условия не выполнены, очищаем конфликты')
    clearConflicts()
  }
}, { immediate: true })
</script>

<style scoped>
/* UI Kit v2 + Bento Grid адаптивность */

@media (max-width: 767px) {
  .order-first {
    order: -1;
  }
  
  .md\:sticky {
    position: static !important;
  }
  
  .md\:z-10 {
    z-index: auto !important;
  }
  
  .space-y-4 > * + * {
    margin-top: 1rem;
  }
}

@media (min-width: 768px) {
  .md\:order-last {
    order: 1;
  }
  
  .md\:sticky {
    position: sticky;
    top: 1.5rem;
  }
  
  .md\:space-y-6 > * + * {
    margin-top: 1.5rem;
  }
}

.contain-layout {
  contain: layout style;
}


</style>