import type { Language } from './i18n'

const uzbekTaxonomy: Record<string, string> = {
  'Аудиооборудование': 'Audio uskunalar',
  'Видеотехника': 'Video uskunalar',
  'Кабельная продукция и коммутация': 'Kabel mahsulotlari va kommutatsiya',
  'Компьютерное и сетевое оборудование': 'Kompyuter va tarmoq uskunalari',
  'Разное / Служебное': 'Turli / xizmat uskunalari',
  'Системы синхронного перевода': 'Sinxron tarjima tizimlari',
  'Транспортировочные и кейс-системы': 'Transport va keys tizimlari',
  'BNC-кабели': 'BNC kabellari',
  'IP Video encode/decoder': 'IP video enkoder/dekoder',
  'MIDI-контроллеры': 'MIDI kontrollerlari',
  'PCI-карты': 'PCI kartalari',
  'PTZ-контроллер': 'PTZ kontrolleri',
  'SFP-модуль': 'SFP moduli',
  'UPS': 'UPS (uzluksiz quvvat manbai)',
  'USB-интерфейсы, HDMI-сплиттеры, контроллеры': 'USB interfeyslar, HDMI splitterlar, kontrollerlar',
  'UTP-кабели': 'UTP kabellari',
  'Wi-Fi роутеры, коммутаторы': 'Wi-Fi routerlar va kommutatorlar',
  'Wi-Fi трансмиттеры': 'Wi-Fi transmitterlar',
  'Адаптеры и переходники': 'Adapterlar va o‘tkazgichlar',
  'Аккумуляторные батареи': 'Akkumulyator batareyalari',
  'Аксессуары для камер': 'Kamera aksessuarlari',
  'Активные акустические системы': 'Faol akustik tizimlar',
  'Аудиоинтерфейсы': 'Audio interfeyslar',
  'Аудиопроцессоры': 'Audio protsessorlar',
  'Беспроводная точка доступа': 'Simsiz kirish nuqtasi',
  'Беспроводная точка доступа с Dante': 'Dante bilan simsiz kirish nuqtasi',
  'Беспроводной конференц-пульт': 'Simsiz konferensiya pulti',
  'Видеовходной блок': 'Video kirish bloki',
  'Видеоинтерфейсы (конвертеры HDMI/SDI)': 'Video interfeyslar (HDMI/SDI konverterlari)',
  'Видеокабели (HDMI, SDI, VGA, DVI)': 'Video kabellar (HDMI, SDI, VGA, DVI)',
  'Видеокамеры (ENG, PTZ, DSLR)': 'Videokameralar (ENG, PTZ, DSLR)',
  "Видеомикшеры (switcher'ы)": 'Video miksherlar (switcherlar)',
  'Видеопроцессоры': 'Video protsessorlar',
  'Видеорекордеры': 'Video rekorderlar',
  'Внешние PCIe-корпуса (Expansion Chassis)': 'Tashqi PCIe korpuslar (Expansion Chassis)',
  'Внешние устройства хранения данных': 'Tashqi ma’lumot saqlash qurilmalari',
  'Захват видео (capture-карты)': 'Video tasvirga olish (capture kartalari)',
  'ИК-передатчик': 'IQ uzatgich',
  'Катушки, стойки, сумки, рюкзаки': 'G‘altaklar, stendlar, sumkalar va ryukzaklar',
  'Кейс для зарядки и хранения инфракрасных приемников': 'Infraqizil qabul qilgichlarni quvvatlash va saqlash keysi',
  'Кейсы (rack-case, flight-case)': 'Keyslar (rack-case, flight-case)',
  'Компьютеры': 'Kompyuterlar',
  'Микрофоны (проводные, беспроводные, головные, петличные)': 'Mikrofonlar (simli, simsiz, bosh va yoqa)',
  'Микшерные пульты (аналоговые/цифровые)': 'Miksher pultlari (analog/raqamli)',
  'Мониторы': 'Monitorlar',
  'Мониторы (режиссёрские, трансляционные)': 'Monitorlar (rejissyorlik va translyatsiya)',
  'Мультимедийный процессор': 'Multimedia protsessori',
  'Ноутбуки': 'Noutbuklar',
  'Периферийное оборудование для конференц-систем': 'Konferensiya tizimlari uchun periferik uskunalar',
  'Периферия': 'Periferiya',
  'Портативные мониторы': 'Portativ monitorlar',
  'Приемники синхронного перевода': 'Sinxron tarjima qabul qilgichlari',
  'Проводной конференц-пульт': 'Simli konferensiya pulti',
  'Пульт делегата': 'Delegat pulti',
  'Радиосистемы': 'Radio tizimlar',
  'Сетевой расширитель для конференц-систем': 'Konferensiya tizimlari uchun tarmoq kengaytirgichi',
  'Стол переводчика': 'Tarjimon pulti',
  'ТВ': 'Televizorlar',
  'Термальный принтер': 'Termal printer',
  'Цифровой контроллер конференц-системы': 'Konferensiya tizimining raqamli kontrolleri',
  'Штативы для колонок': 'Akustik tizimlar uchun stendlar',
}

export function translateEquipmentTaxonomy(value: string | null | undefined, language: Language) {
  if (!value) return ''
  return language === 'uz' ? uzbekTaxonomy[value] ?? value : value
}
