// src/shared/ui-v2/lib/icons.js
// Центральный справочник иконок для проекта EPR System.
// Здесь мы статически импортируем все иконки, используемые в UI Kit v2.
// Это гарантирует, что Vite всегда будет включать их в финальную сборку.

import {
  Package,
  Home,
  X,
  XCircle,
  Plus,
  ChevronDown,
  ChevronUp,
  MoreHorizontal,
  Search,
  User,
  Users,
  Camera,
  AlertCircle,
  AlertTriangle,
  RefreshCw,
  PackageX,
  ChevronLeft,
  ChevronRight,
  Trash2,
  Save,
  Eye,
  Edit,
  MoreVertical,
  Check,
  MapPin,
  CheckCircle,
  TrendingUp,
  TrendingDown,
  List,
  ListPlus,
  Settings,
  ArrowRight,
  Link,
  ExternalLink,
  Inbox,
  Calendar,
  CalendarCheck,
  Copy,
  Download,
  Info,
  Bell,
  Lock,
  Mail,
  LogIn,
  WifiOff,
  FileText,
  Palette
} from 'lucide-vue-next';

export const icons = {
  package: Package,
  home: Home,
  x: X,
  'x-circle': XCircle,
  plus: Plus,
  'chevron-down': ChevronDown,
  'chevron-up': ChevronUp,
  'more-horizontal': MoreHorizontal,
  search: Search,
  user: User,
  users: Users,
  camera: Camera,
  'alert-circle': AlertCircle,
  'alert-triangle': AlertTriangle,
  'refresh-cw': RefreshCw,
  'package-x': PackageX,
  'chevron-left': ChevronLeft,
  'chevron-right': ChevronRight,
  'trash-2': Trash2,
  save: Save,
  eye: Eye,
  edit: Edit,
  'more-vertical': MoreVertical,
  check: Check,
  'map-pin': MapPin,
  'check-circle': CheckCircle,
  'trending-up': TrendingUp,
  'trending-down': TrendingDown,
  list: List,
  'list-plus': ListPlus,
  settings: Settings,
  'arrow-right': ArrowRight,
  link: Link,
  'external-link': ExternalLink,
  inbox: Inbox,
  calendar: Calendar,
  'calendar-check': CalendarCheck,
  copy: Copy,
  download: Download,
  info: Info,
  bell: Bell,
  lock: Lock,
  mail: Mail,
  'log-in': LogIn,
  'wifi-off': WifiOff,
  'file-text': FileText,
  palette: Palette
};

export function getIcon(name) {
  return icons[name] || null;
}
